/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
 */

package code;

import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelosBean.EPI;
import modelosBean.EPIMarca;
import modelosDAO.EPIDAO;
import modelosDAO.EPIMarcaDAO;

/**
 *
 * @author guidi
 */
public class cadastroEPI extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastroEPI
     */
    public cadastroEPI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nomeMarca = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoMarca = new javax.swing.JTextArea();
        CA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dataCA = new javax.swing.JFormattedTextField();
        maximo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        minimo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomeEPI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro EPI novo");

        jLabel14.setText("Nome Marca ");

        jLabel15.setText("C.A.");

        jLabel16.setText("Informações adicionais");

        nomeMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMarcaActionPerformed(evt);
            }
        });

        jButton3.setText("Cadastrar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        descricaoMarca.setColumns(20);
        descricaoMarca.setRows(5);
        jScrollPane1.setViewportView(descricaoMarca);

        CA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAActionPerformed(evt);
            }
        });

        jLabel1.setText("Data de Validade C.A.");

        try {
            dataCA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        maximo.setText("000");

        jLabel7.setText("Máximo");

        minimo.setText("000");
        minimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimoActionPerformed(evt);
            }
        });

        jLabel6.setText("Minimo");

        nomeEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEPIActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                        .addComponent(minimo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(maximo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeMarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataCA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeEPI)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(nomeEPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(maximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(nomeMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(CA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dataCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEPIActionPerformed

    private void minimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Botão Cadastrar deve:
        // Confirmar  se o mesmo produto não está cadastrado e confirmar se os dados estão corretos na tela antes de  inserir no banco de dados
        //checar se a data é uma data 
        String nomeEPIString, marcaEPIString,CAString,dataCAString,minimoString, maximoString, informacoesString;
        CAString  = this.CA.getText();
        nomeEPIString = this.nomeEPI.getText();
        marcaEPIString = this.nomeMarca.getText();
        minimoString = this.minimo.getText();
        maximoString = this.maximo.getText();
        informacoesString = this.descricaoMarca.getText();
        dataCAString =this.dataCA.getText();
        int minimoInt,maximoInt;
        minimoInt = Integer.parseInt(minimoString);
        maximoInt = Integer.parseInt(maximoString);
        String[] datasplited;
        datasplited = dataCAString.split("/");
        Date dataFinal;
        dataFinal = new Date(Integer.parseInt(datasplited[2]), Integer.parseInt(datasplited[1]), Integer.parseInt(datasplited[0]));
        EPIMarca finale;
        finale = new EPIMarca( nomeEPIString ,maximoInt, minimoInt , informacoesString ,CAString , dataFinal, marcaEPIString);
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja adicionar o Seguinte EPI : \n Nome : "+ finale.getNome() +"\n Marca: " +finale.getMarca() + "\n C.A. : " + finale.getCA()+ "\n Para adicionar clique em OK" ) ){
           if(EPIMarcaDAO.criaEPIMarca(finale)){
               JOptionPane.showMessageDialog(null, "Item adicionado com sucesso!!");
           }else{
               JOptionPane.showMessageDialog(null, "Falha ao adicionar\n motivo: \n Item já adicionado!!");
           }
        }
        
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nomeMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMarcaActionPerformed

    private void CAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CA;
    private javax.swing.JFormattedTextField dataCA;
    private javax.swing.JTextArea descricaoMarca;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maximo;
    private javax.swing.JTextField minimo;
    private javax.swing.JTextField nomeEPI;
    private javax.swing.JTextField nomeMarca;
    // End of variables declaration//GEN-END:variables
}
