/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
 */

package code;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelosBean.EPIMarca;
import modelosBean.consumivel;
import modelosBean.ferramenta;
import modelosDAO.EPIMarcaDAO;
import modelosDAO.consumivelDAO;
import modelosDAO.ferramentaDAO;

/**
 *
 * @author guidi
 */
public class checaEstoqueEPI extends javax.swing.JInternalFrame {
    private ArrayList<EPIMarca> epis;
    private ArrayList<consumivel> consu;
    private ArrayList<ferramenta> ferr;
    private   DefaultTableModel tabela;
    /**
     * Creates new form checaEstoqueEPI
     */
    public checaEstoqueEPI() {
        initComponents();
         try {
            atualizaEPI();
             }catch(SQLException| ClassNotFoundException e){
                 System.out.println(e);
             }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText("Exibir Estoque ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Marca", "Quantidade", "CA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

             try {
            atualizaEPI();
             }catch(SQLException| ClassNotFoundException e){
                 System.out.println(e);
             }
        


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private void atualizaEPI() throws SQLException, ClassNotFoundException {
        this.epis = EPIMarcaDAO.retornaEPIMarcaArray();
        this.tabela = (DefaultTableModel) this.jTable1.getModel();
        this.tabela.setRowCount(0);
        int aux = 0;
        for(EPIMarca e : this.epis){
            this.tabela.setRowCount(aux+1);
            tabela.setValueAt(e.getNome(), aux, 0);
            tabela.setValueAt(e.getMarca(), aux, 1);
            tabela.setValueAt(e.getQuantidade(), aux, 2);
            tabela.setValueAt(e.getCA(), aux, 3);
            aux++;
        }
      
       
    }

    private void atualizaConsumivel() {

            this.consu = consumivelDAO.listaConsumivel();
            this.tabela = (DefaultTableModel) this.jTable1.getModel();
            this.tabela.getColumnCount();
            this.tabela.setRowCount(0);
            int aux = 0;
            for(consumivel e : this.consu){
                this.tabela.setRowCount(aux+1);
                tabela.setValueAt(e.getNome(), aux, 0);
                tabela.setValueAt(e.getMarca(), aux, 1);
                tabela.setValueAt(e.getQuantidade(), aux, 2);
                aux++;
            }
       
    }

    private void atualizaFerramenta() {
       this.ferr = ferramentaDAO.retornaFerramentaArray();
       if(this.ferr == null){
           JOptionPane.showMessageDialog(rootPane, "Erro de acesso ao Banco de Dados");
       }else{
           this.tabela = (DefaultTableModel) this.jTable1.getModel();
            this.tabela.setRowCount(0);
            int aux = 0;
            for(ferramenta e : this.ferr){
                this.tabela.setRowCount(aux+1);
                tabela.setValueAt(e.getNome(), aux, 0);
                tabela.setValueAt(e.getMarca(), aux, 1);
                if(e.getTipo()==0){
                     if(e.getStat()==1){
                     tabela.setValueAt("Item emprestado", aux, 2);
                }else{
                     tabela.setValueAt("Item disponível", aux, 2);
                }
                }
                if(e.getTipo()==1){
                     tabela.setValueAt(e.getQuantidade(), aux, 2);
                }
               
               
                aux++;
       } 
    }
}

}
