/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
 */

package code;

import java.sql.SQLException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelosBean.requisicao;
import modelosBean.requisicaoCompleta;
import modelosDAO.funcionarioDAO;
import modelosDAO.requisicaoCompletaDAO;
import static modelosDAO.requisicaoDAO.autorizaRequisicao;
import static modelosDAO.requisicaoDAO.negaRequisicao;
import modelosDAO.responsavelDAO;

/**
 *
 * @author guidi
 */
public class detalhesRequisicao extends javax.swing.JInternalFrame {
    private  requisicao req;

    /**
     * Creates new form detalhesRequisicao
     * @param cod
     */
    public detalhesRequisicao(int cod) throws SQLException, ClassNotFoundException {
        initComponents();
        requisicaoCompleta soli;
        soli = requisicaoCompletaDAO.retornaRequisicaoCompleta(cod);
        this.req = soli.getRequisicaoCabeca();
        String nomeFunc;
        nomeFunc = funcionarioDAO.nomeFuncionarioCod(this.req.getCodFuncionario());
        System.out.println(nomeFunc);
        this.nomeFuncionario.setText( nomeFunc);
        String nomeResp;
        nomeResp = responsavelDAO.nomeResponsavelCod(this.req.getCodResponsavel());
        this.nomeResponsavel.setText(nomeResp);
        Date data;
        data = new Date( this.req.getHora().getTime() );
        SimpleDateFormat formatar;
        formatar = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada;
        dataformatada = formatar.format(data);
        this.dataSolicitacao.setText(dataformatada);
        Time hora;
        hora  = new Time(this.req.getHora().getTime());
        SimpleDateFormat formatarHora;
        formatarHora  = new SimpleDateFormat("hh:mm:ss");
        formatarHora.setTimeZone(TimeZone.getTimeZone("GMT -3"));  
        String horaFormatada;
        horaFormatada  = formatarHora.format(hora);
        this.horaSolicitacao.setText(horaFormatada);
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeResponsavel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dataSolicitacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        horaSolicitacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Autorizar Solicitação ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data da solicitação");

        nomeResponsavel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeResponsavel.setText(" ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Responsável ");

        dataSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataSolicitacao.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Hora da solicitação");

        nomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeFuncionario.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Funcionario ");

        horaSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        horaSolicitacao.setText(" ");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EPI", "Quantidade ", "Último Pedido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Autorizar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Negar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(dataSolicitacao)
                            .addComponent(nomeResponsavel)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horaSolicitacao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(nomeFuncionario)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(horaSolicitacao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addComponent(nomeResponsavel)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(dataSolicitacao)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
                // TODO add your handling code here:
                /**
                 * Deve alterar o status para autorizado 1
                 */
        
                try{
                    if(0 == JOptionPane.showConfirmDialog(null, "Deseja autorizar essa saída ?")){
                        if(autorizaRequisicao(this.req.getCod())){
                        JOptionPane.showMessageDialog(rootPane, "Autorizada com suceso!!");
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Falha de acesso ao Banco de Dados !");
                        } 
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Operação Cancelada !");
                    }
                   
                }catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
                    if(0 == JOptionPane.showConfirmDialog(null, "Deseja Negar essa saída ?")){
                        if(negaRequisicao(this.req.getCod())){
                        JOptionPane.showMessageDialog(rootPane, "Negada com suceso!!");
                        this.dispose();
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Falha de acesso ao Banco de Dados !");
                        } 
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Operação Cancelada !");
                    }
                   
                }catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataSolicitacao;
    private javax.swing.JLabel horaSolicitacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JLabel nomeResponsavel;
    // End of variables declaration//GEN-END:variables
}
