/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
 */

package code;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelosBean.EPIMarca;
import modelosBean.funcionario;
import modelosBean.itemRequisicao;
import modelosBean.itemRequisicaoCompleta;
import modelosBean.requisicao;
import modelosBean.requisicaoCompleta;
import modelosBean.responsavel;
import modelosDAO.EPIMarcaDAO;
import static modelosDAO.funcionarioDAO.listaFuncionarioArray;
import modelosDAO.requisicaoCompletaDAO;
import modelosDAO.responsavelDAO;
import static modelosDAO.responsavelDAO.listaResponsavelArray;

/**
 *
 * @author guidi
 */
public class saidaEPI extends javax.swing.JInternalFrame {
    private final ArrayList<funcionario> a;
    private final ArrayList<responsavel> c;
    private requisicao req;
    private ArrayList<itemRequisicaoCompleta> itens;
    private ArrayList<EPIMarca> total;
    private EPIMarca selected;
    /**
     * Creates new form saidaEPI
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public saidaEPI() throws SQLException, ClassNotFoundException {
        initComponents();
        //Preenchimento dos Combo Box
        this.itens = new ArrayList<>();
        a =listaFuncionarioArray();
            for(funcionario lat: a ){
                this.selecionaFuncionario.addItem(lat.getNome());
                }
            total = EPIMarcaDAO.retornaEPIMarcaArray();
        c = listaResponsavelArray();
       
            
          //  this.selecionaItem.setEnabled(false);
            this.selecionaQuantidade.setEnabled(false);
            this.geraSolicitacao.setEnabled(false);
            this.addRequisicao.setEnabled(false);
            this.CADigitado.setEnabled(false);
    }
    private void marcaEPIs(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selecionaFuncionario = new javax.swing.JComboBox();
        selecionaQuantidade = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        addRequisicao = new javax.swing.JButton();
        geraSolicitacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CADigitado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomeEPI = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Saída EPI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("CA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Funcionário");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selecionaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        selecionaFuncionario.setNextFocusableComponent(jButton1);

        selecionaQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selecionaQuantidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", " " }));
        selecionaQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaQuantidadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Quantidade ");

        addRequisicao.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        addRequisicao.setText("Adicionar");
        addRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRequisicaoActionPerformed(evt);
            }
        });

        geraSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        geraSolicitacao.setText("Gerar Solicitação");
        geraSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraSolicitacaoActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        CADigitado.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        CADigitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADigitadoActionPerformed(evt);
            }
        });
        CADigitado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADigitadoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        jLabel1.setText("Nome EPI");

        NomeEPI.setFont(new java.awt.Font("sansserif", 0, 22)); // NOI18N
        NomeEPI.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(CADigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeEPI)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(selecionaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addRequisicao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(geraSolicitacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selecionaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecionaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeEPI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CADigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selecionaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addRequisicao)
                        .addGap(2, 2, 2)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(geraSolicitacao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRequisicaoActionPerformed
       if(this.selected != null){
        // TODO add your handling code here:
       int index;
       index = this.itens.size();
      // gera um itemRequisicaoCompleta e coloca no array list
      int itemIndex, itemCod,quantidadeInt;
      itemCod = this.selected.getCod();
      quantidadeInt = this.selecionaQuantidade.getSelectedIndex() + 1;
      this.itens.add(new itemRequisicaoCompleta(itemCod, quantidadeInt));
        System.out.println(this.itens.size());
      // adiciona esse item a tabela 
      DefaultTableModel defaultModel =  (DefaultTableModel) this.jTable1.getModel();
      //  ITEM QUANTIDADE
   
       Object item ,quant;
      item = this.selected.getNome();
      quant = quantidadeInt;
      defaultModel.setRowCount(index + 1);
        this.jTable1.getModel().setValueAt(item, index, 0);
        this.jTable1.getModel().setValueAt(quant, index, 1);
        this.geraSolicitacao.setEnabled(true);
      }else{
           JOptionPane.showMessageDialog(rootPane, "Digite um CA  válido");
       }
     
    }//GEN-LAST:event_addRequisicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //bloqueia o campo de funcionário  e libera os outros.
        this.selecionaFuncionario.setEnabled(false);
        this.jButton1.setEnabled(false);
        this.addRequisicao.setEnabled(true);
        this.selecionaQuantidade.setEnabled(true);
        this.CADigitado.setEnabled(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selecionaQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionaQuantidadeActionPerformed

    private void geraSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraSolicitacaoActionPerformed
        // TODO add your handling code here:
            requisicaoCompleta ultima;
            
            Boolean envio;
            String senha;
            try {
                senha =  JOptionPane.showInputDialog("Digite a Senha do Responsável.");
                int resSenha;
                resSenha = responsavelDAO.checaSenhaInt(senha);
                if(0 < resSenha){
                    int codFunc;
                    codFunc = this.selecionaFuncionario.getSelectedIndex();
                    codFunc = this.a.get(codFunc).getCod();
                    req = new requisicao(codFunc, resSenha);
                    System.out.println(req);
                    ultima = new requisicaoCompleta(itens, req);
                    if(requisicaoCompletaDAO.checaItens(ultima)){
                    envio = requisicaoCompletaDAO.insereRequisicaoCompleta(ultima);
                    JOptionPane.showMessageDialog(null, "Solicitação efetuada com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário");
                }
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(saidaEPI.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultTableModel defaultModel =  (DefaultTableModel) this.jTable1.getModel();
            defaultModel.setRowCount(0);
            this.itens.clear();
            req = null;
            this.selecionaQuantidade.setEnabled(false);
            this.geraSolicitacao.setEnabled(false);
            this.addRequisicao.setEnabled(false);
            this.selecionaFuncionario.setEnabled(true);
            this.jButton1.setEnabled(true);    
    }//GEN-LAST:event_geraSolicitacaoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void CADigitadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADigitadoKeyReleased
        // TODO add your handling code here:
        String value;
        value =  this.CADigitado.getText().toLowerCase();
        for(EPIMarca a: this.total){
            if(a.getCA().toLowerCase().contains(value)){
                this.NomeEPI.setText(a.getNome());
                this.selected= a;
                return;
            }
        }
        this.NomeEPI.setText("Não encontrado");
        this.selected = null;
        
    }//GEN-LAST:event_CADigitadoKeyReleased

    private void CADigitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADigitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CADigitadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CADigitado;
    private javax.swing.JLabel NomeEPI;
    private javax.swing.JButton addRequisicao;
    private javax.swing.JButton geraSolicitacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox selecionaFuncionario;
    private javax.swing.JComboBox selecionaQuantidade;
    // End of variables declaration//GEN-END:variables
}
