/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
 */

package code;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelosBean.EPI;
import modelosBean.funcionario;
import modelosBean.itemRequisicao;
import modelosBean.marcaEPI;
import modelosBean.requisicao;
import modelosBean.requisicaoCompleta;
import modelosBean.responsavel;
import modelosDAO.EPIDAO;
import static modelosDAO.funcionarioDAO.listaFuncionario;
import modelosDAO.requisicaoCompletaDAO;
import static modelosDAO.responsavelDAO.listaResponsavel;

/**
 *
 * @author guidi
 */
public class saidaEPI extends javax.swing.JInternalFrame {
    private final ArrayList<funcionario> a;
    private final ArrayList<EPI> b;
    private final ArrayList<responsavel> c;
    private requisicao req;
    private ArrayList<itemRequisicao> itens;
    private ArrayList<marcaEPI> marcas;
    /**
     * Creates new form saidaEPI
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public saidaEPI() throws SQLException, ClassNotFoundException {
        initComponents();
        //Preenchimento dos Combo Box
        this.itens = new ArrayList<>();
        ResultSet funcionarios;
        funcionarios =listaFuncionario();
        a =new ArrayList<>();
            while(funcionarios.next()){
                this.selecionaFuncionario.addItem(funcionarios.getString("nome"));
                a.add(new funcionario(funcionarios.getInt("cod"),funcionarios.getString("nome"), funcionarios.getInt("funcao"), funcionarios.getString("admissao")));
        }
        ResultSet epis;
        epis = EPIDAO.listaEPI();
        b = new ArrayList<>();
            while(epis.next()){
                this.selecionaItem.addItem(epis.getString("nome"));
                b.add(new EPI(epis.getInt("cod"), epis.getString("nome")));
        }
        ResultSet responsaveis;
        c = new ArrayList<>();
        responsaveis = listaResponsavel();
        while(responsaveis.next()){
            System.out.println(responsaveis.getInt("cod"));
                this.selecionaResponsavel.addItem(responsaveis.getString("nome"));
                c.add(new responsavel(responsaveis.getString("nome"), responsaveis.getInt("cod")));
        }
        
            
          //  this.selecionaItem.setEnabled(false);
            this.selecionaQuantidade.setEnabled(false);
            this.geraSolicitacao.setEnabled(false);
            this.addRequisicao.setEnabled(false);
            this.selecionaItem.setEnabled(false);
    }
    private void marcaEPIs(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selecionaResponsavel = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selecionaFuncionario = new javax.swing.JComboBox();
        selecionaItem = new javax.swing.JComboBox();
        selecionaQuantidade = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        addRequisicao = new javax.swing.JButton();
        geraSolicitacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        SelecionaMarcaEPI = new javax.swing.JComboBox();

        setClosable(true);
        setResizable(true);
        setTitle("Saída EPI");
        setNextFocusableComponent(selecionaResponsavel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Responsável pela Saída ");

        selecionaResponsavel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selecionaResponsavel.setNextFocusableComponent(selecionaFuncionario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Adicionar item ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Funcionário");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selecionaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selecionaFuncionario.setNextFocusableComponent(jButton1);

        selecionaItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        selecionaQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selecionaQuantidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", " " }));
        selecionaQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaQuantidadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade ");

        addRequisicao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addRequisicao.setText("Adicionar");
        addRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRequisicaoActionPerformed(evt);
            }
        });

        geraSolicitacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        geraSolicitacao.setText("Gerar Solicitação");
        geraSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geraSolicitacaoActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Marca");

        SelecionaMarcaEPI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SelecionaMarcaEPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionaMarcaEPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionaResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(selecionaFuncionario, 0, 239, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(68, 68, 68))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(selecionaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(selecionaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SelecionaMarcaEPI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(addRequisicao)
                                .addGap(70, 70, 70))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(geraSolicitacao)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selecionaResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(selecionaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRequisicao)
                    .addComponent(selecionaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelecionaMarcaEPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(geraSolicitacao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRequisicaoActionPerformed
        // TODO add your handling code here:
       int index;
       index = this.itens.size();
      // gera um item solicitação e coloca no array list
      int itemIndex, itemCod;
      itemIndex = this.selecionaItem.getSelectedIndex();
      itemCod = this.b.get(itemIndex).getCod();
      int quantidadeInt;
      quantidadeInt = this.selecionaQuantidade.getSelectedIndex() + 1;
      this.itens.add(new itemRequisicao(itemCod, quantidadeInt));
        System.out.println(this.itens.size());
      // adiciona esse item a tabela 
      DefaultTableModel defaultModel =  (DefaultTableModel) this.jTable1.getModel();
      
      //  ITEM QUANTIDADE
      Object item ,quant;
      item = this.b.get(itemIndex).getNome();
      quant = quantidadeInt;
      defaultModel.setRowCount(index + 1);
        this.jTable1.getModel().setValueAt(item, index, 0);
        this.jTable1.getModel().setValueAt(quant, index, 1);
        this.geraSolicitacao.setEnabled(true);
    }//GEN-LAST:event_addRequisicaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.selecionaResponsavel.setEnabled(false);
        this.selecionaFuncionario.setEnabled(false);
        this.jButton1.setEnabled(false);
        this.addRequisicao.setEnabled(true);
        this.selecionaItem.setEnabled(true);
        this.selecionaQuantidade.setEnabled(true);
        int funcIndex, respIndex, funcInt,respInt;
        funcIndex= this.selecionaFuncionario.getSelectedIndex();
        funcInt = this.a.get(funcIndex).getCod();
        respIndex = this.selecionaResponsavel.getSelectedIndex();
        respInt = this.c.get(respIndex).getCod();
        this.req = new requisicao(funcInt, respInt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selecionaQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionaQuantidadeActionPerformed

    private void geraSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geraSolicitacaoActionPerformed
        // TODO add your handling code here:
        requisicaoCompleta ultima;
        ultima = new requisicaoCompleta(req, itens);
        Boolean envio; 
            try {
                if(0==JOptionPane.showInternalConfirmDialog(rootPane,"Confirmar solicitação?")){
                    envio = requisicaoCompletaDAO.insereRequisicaoCompleta(ultima);
                    JOptionPane.showMessageDialog(null, "Solicitação efetuada com sucesso!");
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário");
                }       
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(saidaEPI.class.getName()).log(Level.SEVERE, null, ex);
            }
             DefaultTableModel defaultModel =  (DefaultTableModel) this.jTable1.getModel();
             defaultModel.setRowCount(0);
            this.itens.clear();
            req = null;
            this.selecionaQuantidade.setEnabled(false);
            this.geraSolicitacao.setEnabled(false);
            this.addRequisicao.setEnabled(false);
            this.selecionaItem.setEnabled(false);
            this.selecionaResponsavel.setEnabled(true);
            this.selecionaFuncionario.setEnabled(true);
            this.jButton1.setEnabled(true);
            
        
        
        
    }//GEN-LAST:event_geraSolicitacaoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void SelecionaMarcaEPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionaMarcaEPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecionaMarcaEPIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SelecionaMarcaEPI;
    private javax.swing.JButton addRequisicao;
    private javax.swing.JButton geraSolicitacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox selecionaFuncionario;
    private javax.swing.JComboBox selecionaItem;
    private javax.swing.JComboBox selecionaQuantidade;
    private javax.swing.JComboBox selecionaResponsavel;
    // End of variables declaration//GEN-END:variables
}
