/*
 * Developed by Guilherme Nassi
 * Do not remove this header
 * You can use this code as long as this header is in it.
kakakakakaakakaka
 */

package code;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelosBean.EPI;
import modelosBean.EPIMarca;
import modelosBean.estoqueEPI;
import modelosDAO.EPIMarcaDAO;
import static modelosDAO.EPIMarcaDAO.adicionaQuantidadeEPI;
import modelosDAO.estoqueEPIDAO;

/**
 *
 * @author guidi
 */
public class entradaEPI extends javax.swing.JInternalFrame {
    private ArrayList<estoqueEPI> list;
    private ArrayList<EPIMarca> epis;
    private EPIMarca selecionado;
    
    /**
     * Creates new form entradaEPI
     */
    public entradaEPI() throws SQLException, ClassNotFoundException {
        initComponents();
        this.list = estoqueEPIDAO.retornaEPIEstoque();
        epis = EPIMarcaDAO.retornaEPIMarcaArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Quantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CADigitado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeEPI = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Adicionar EPI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("CA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Quantidade a ser Adicionada");

        Quantidade.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText("Adicionar ao total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CADigitado.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        CADigitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADigitadoActionPerformed(evt);
            }
        });
        CADigitado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CADigitadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CADigitadoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("EPI");

        nomeEPI.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        nomeEPI.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Quantidade)
                        .addGap(408, 408, 408))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(302, 302, 302))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CADigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(nomeEPI, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CADigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeEPI))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int quantidade;
        quantidade = Integer.parseInt(this.Quantidade.getText());
        if(this.selecionado == null){
            JOptionPane.showMessageDialog(rootPane, "Digite um CA válido");
            this.CADigitado.setText("");
            this.Quantidade.setText("");
            this.nomeEPI.setText(" ");
            this.selecionado = null;
        }else{
            this.selecionado.setQuantidade(quantidade);
            if (0==JOptionPane.showConfirmDialog(rootPane, "confirma Adição  de " + this.selecionado.getQuantidade() + "\n Ao EPI " + this.selecionado.getNome())){
               if(adicionaQuantidadeEPI(this.selecionado)){
                   JOptionPane.showMessageDialog(rootPane, "Adicionado com sucesso");
                   
               }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Operação Cancelada pelo Usuario!!");
            }
            
                    
        }
         this.CADigitado.setText("");
         this.Quantidade.setText("");
         this.nomeEPI.setText(" ");
         this.selecionado = null;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CADigitadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADigitadoKeyTyped

    }//GEN-LAST:event_CADigitadoKeyTyped

    private void CADigitadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CADigitadoKeyReleased
        // TODO add your handling code here:  // TODO add your handling code here:
        String value;
        value =  this.CADigitado.getText();
        for(EPIMarca a: this.epis){
            if(a.getCA().toLowerCase().contains(value)){
                this.nomeEPI.setText(a.getNome());
                this.selecionado = a;
                return;
            }
        }
        this.nomeEPI.setText("Não encontrado");
        this.selecionado = null;
        
    }//GEN-LAST:event_CADigitadoKeyReleased

    private void CADigitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADigitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CADigitadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CADigitado;
    private javax.swing.JTextField Quantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeEPI;
    // End of variables declaration//GEN-END:variables
}
